server:
  port: 8098
  servlet:
    context-path: /rabbit
spring:
  rabbitmq:
    host: 101.43.244.29
    port: 5673
    username: guest
    password: guest
      #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
      #保证交换机能把消息推送到队列中
    publisher-returns: true
    virtual-host: /
      #这个配置是保证消费者会消费消息，手动确认
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
  redis:
    host: 101.43.244.29
    port: 6379  #可不配，因为底层默认值为6379
#    Auth: 1234
    password: 1234
    database: 0
    timeout: 10000ms
  datasource:
    url: jdbc:mysql://101.43.244.29:3306/middle_ware?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  configuration:
      ### 开启打印sql配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

